name: Test
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install, build
      run: |
        # Build the project
        npm install
        npm run build --if-present
    - name: GitHub Branch Deploy
      uses: zekth/gh-deploy-action@1.0.0
      with:
        build_dir: './dist/jwlmerge-pwa'
        gh_token: ${{ secrets.GH_TOKEN }}
