on:
  push:
    branches:
      - master

env:
  NODE_VERSION: '13.x'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build
      run: |
        # Build the project
        npm install
        npm run build --if-present
    - name: GitHub Branch Deploy
      uses: zekth/gh-deploy-action@1.0.0
      with:
        build_dir: './dist/jwlmerge-pwa'
        gh_token: ${{ secrets.GH_TOKEN }}
